### ISSUE TITLE
How to run a command that includes "await"

### ISSUE THREAD

**Issue by ele0001** [BracketByte/DJS-Handler#2]
Soo.. this is the command runner I guess..
```
module.exports = {
	name: 'ping',
	description: 'Just a test command',
	aliases: [],
	guildOnly: false,
	args: false,
	usage: '',
	execute:(message, args, client) => {
```

Anyways, I have a command that has "await", when I run it in this handler, it says "await" is only valid in async function. I don't know how to turn execute: thing to async run. Please help.

**Comment by BracketByte** [comment]
if you take a look at the help command you will see that it also uses async/await, the way you get your problem foxed is my changing `execute:(message, args, client) => {` to `execute: async (message, args, client) => {`

**Comment by ele0001** [comment]
Thanks!!! You are a life saver!!

**Comment by ele0001** [comment]
Thanks. Giving a star
