### ISSUE TITLE
Without Prefix(Please Reply)

### ISSUE THREAD

**Issue by Hassaan-7676** [BracketByte/DJS-Handler#4]
I wanna add a command that can be used by sending any thing like "hi", "test" without the prefix

**Comment by IHZAQ** [comment]
in `config.json` the prefix value is !. replace it with nothing
```
{
	"prefix": "",
	"colors": {
		"default": "any",
		"error": "any"
	}
}

```
Leave prefix alone

**Comment by GrosuN** [comment]
For those simple cases you can just open the [message](https://github.com/BracketByte/DJS-Handler/blob/main/events/messageCreate.js) event and add your command right before the bot tests for a prefix. 
Hope this helps you. Have a nice day!
