### ISSUE TITLE
Update to Discord.js V13

### ISSUE THREAD

**Issue by Scoooolzs** [BracketByte/DJS-Handler#6]
Update to Discord.js V13... I really wanted to use a discord.js v13, Pleasee Update to discord.js v13.

**Comment by IHZAQ** [comment]
Look at Discord docs by yourself
[Discord docs](https://discordjs.guide/additional-info/changes-in-v13.html)

**Comment by Scoooolzs** [comment]
> Look at Discord docs by yourself [Discord docs](https://discordjs.guide/additional-info/changes-in-v13.html)

I wanted this repo to update v13

**Comment by GrosuN** [comment]
The project just got updated to V13 and it supports basic commands and commands with the use of interactions.

As of this moment the bot has a help command and a test command that work with prefix and interactions, feel free to inspect the given commands and start building your own bot!
